from django.urls import path
from Bigflow.Report import views as report

urlpatterns = [
    path('stocksummary/', report.StockSummaryIndex, name="stock"),
    path('FourLineMis/', report.Four_Line_Mis, name="Four_Line_Mis"),
    path('getsalesandoutstanding/', report.get_totalsales_and_totaloutstanding, name='getsalesandoutstanding'),
    path('stockgett/', report.StockSum, name="stock"),
    path('ovralreport/', report.outstandingReportIndex, name="ovralreport"),
    path('outsummary/', report.out_summary, name='out_summary'),
    path('invsmry_get/', report.invoicesmry_get, name='invoicesmry_get'),
    path('invoicewise_getexcel/', report.invoicesmryy_get, name='invoicesmryy_get'),
    path('brnchsmry_get/', report.branchsmry_get, name='branchsmry_get'),
    path('newovralreport/', report.newoverallReportIndex, name="ovralreport"),
    path('newovralreportsmry/', report.newoverallReportsmryIndex, name="newoverallReportsmryIndex"),
    path('ppr_report/', report.report_PPR_main, name="report_main"),
    path('PPR_report_url/', report.PPR_report_url, name="PPR_report_url"),
    path('Generate_PPR_XL/', report.Generate_PPR_XL, name='Generate_PPR_XL'),
    path('ppr_schudle/', report.PPR_Schudle, name='ppr_schudle'),
    path('ppr_supplier_report/', report.ppr_supplier_report, name="ppr_supplier_report"),
    path("budget_summary/", report.Budget_Summary, name="budget_summary"),
    path('ppr_budget_get_summary/', report.PPR_Budget_Get_Summary, name='ppr_budget_get_summary'),
    path('budget_excel/', report.PPR_Budget_Excel_Upload, name="budget_excel"),
    path('PPR_Upload_XL/', report.PPR_Budget_Upload_XL_genetate_Json, name="PPR_Upload_XL"),
    path('PPR_Buget_XL_Set/', report.PPR_Buget_XL_Set, name="PPR_Buget_XL_Set"),
    path('budget_builder/', report.Budget_builder, name="budget_builder"),
    path('budget_reviewer/',report.Budget_reviewer,name="budget_reviewer"),
    path('budget_approval/',report.Budget_approval,name="budget_approval"),
    path('customer_name/', report.custname_get, name='custname_get'),
    path('customergroup_name/', report.custgrpname_get, name='custgrpname_get'),
    path('employee_name/', report.employeename_get, name='employeename_get'),
    path('get_Outstanding_comparison/', report.get_Outstanding_comparison, name='get_Outstanding_comparison'),
    path('outstandingExcel/', report.outstandingExcel, name='outstanding download'),
    path('get_Attendance_MIS/', report.get_Attendance_MIS, name='Attendance_MIS'),
    path('get_FollowUp_MIS/', report.get_FollowUp_MIS, name='FollowUp_MIS'),
    path('get_FollowUp>90_MIS/', report.get_FollowUp_90_MIS, name='FollowUp_MIS'),
    path('get_FollowUp>60_MIS/', report.get_FollowUp_60_MIS, name='get_FollowUp_60_MIS'),

    path('get_Chequesinclear_MIS/', report.get_Chequesinclear_MIS, name='Cheques_MIS'),
    path('querysummary/', report.querysummaryIndex, name='querysummary'),
    path('setupdate/', report.setupdate, name='setupdate'),
    path('salecontrolsheet/', report.Controlsheet, name='Controlsheet'),
    path('Control_Sheet/', report.Control_Sheet, name='Control_Sheet'),
    path('controlsheetsummary/', report.Control_Sheet_summary, name='Control_Sheet_summary'),
    path('getControl_Sheet/', report.getControl_Sheet, name='getControl_Sheet'),
    path('getComparesale/', report.getComparesale, name='getComparesale'),
    path('outstandingcontrolsheet/', report.os_Controlsheet, name='os_Controlsheet'),
    path('stockcontrolsheet/', report.stock_controlsheet, name='stock_controlsheet'),
    path('performance_getexcel/', report.performance_excel, name='performance_getexcel'),
    path('getCompareos/', report.getCompareos, name='getCompareos'),
    path('stock_sumry_rpt/', report.stcksumry_overall_rept, name='stcksumry_overall_rept'),
    path('pr_po_query/', report.pr_po_query, name="pr_po_query"),
    path('get_alltable/', report.get_alltable, name="get_alltable"),
    path('Pr_Po_data/', report.Pr_Po_data, name="Pr_Po_data"),
    # path('agentsummary/', report.agentsummary, name='agentsummary'),
    path('trandatadetails/', report.trandatadetails, name='trandatadetails'),
    path('master_sync_data/', report.master_sync_data, name='master_sync_data'),
    path('master_sync_employee/', report.master_sync_employee, name='master_sync_employee'),
    path('master_sync_branch/', report.master_sync_branch, name='master_sync_branch'),
    path('master_sync_gl/', report.master_sync_gl, name='master_sync_gl'),

    path('Master_Sync_Data/', report.master_sync_get, name='Master_Sync_Data'),
    path('Master_Employee_Data/', report.master_sync_employee_get, name='master_sync_employee_get'),
    path('Master_Branch_Data/', report.master_sync_branch_get, name='master_sync_branch_get'),
    path('Master_Gl_Data/', report.master_sync_gl_get, name='master_sync_gl_get'),
    # path('reftable/', report.reftable, name='reftable')

]
