from django.urls import path
from Bigflow.Master import views
from Bigflow.Transaction import views as transactionview
from Bigflow.Core import views as coreViews

urlpatterns = [
    path('customername/',views.customername,name='customername'),
    path('customergroupname/',views.customergroupname,name='customergroupname'),
    path('saleorder/',views.saleorder,name='saleorder'),
    path('soorderdetails/',views.soorderdetails,name='soorderdetails'),
    path('customerall/',views.customerall,name='customerall'),
    path('casequerys/',views.casequerys,name='casequerys'),
    # path('query/',views.query,name='query')
    path('casequery/',views.casequery,name='casequery'),
    path('followup/',views.followup,name='followup'),
    path('outstanding/', views.outstanding, name='outstanding'),
    path('casequery_temp/', views.casequery_temp, name='casequery_temp'),
    path('sales_transaction/',views.sales_transaction,name='sales_transaction'),
    path('texteditor/', views.texteditor, name='texteditor'),
    path('mailtemplate/', views.mailtemplate, name='mailtemplate'),
    path('mailtemplatesummary/',views.mailtemplatesummary, name='mailtemplatesummary'),
    path('sendmailTemplate/', views.sendmailTemplate, name='sendmailTemplate'),
    path('Templatecreation/', views.Templatecreation, name='Templatecreation'),
    path('EditTemplate/', views.EditTemplate, name='EditTemplate'),
    path('getquerydata/', views.getquerydata, name='getprocessdata'),
    path('MailTemplate_set/',views.MailTemplate_set, name='MailTemplate_set'),
    path('getTemplatedata/', views.getTemplatedata , name='getTemplatedata'),
    path('commentget/',views.commentget,name='commentget'),
    path('commentset/',views.commentset,name='commentset'),
    path('execmappingexcel/',views.execmapping_excel,name='execmapping_excel'),
    path('ddlempexec/',views.employee_executive,name='ddlempexec'),
    path('ddlempexecall/',views.employee_allexecutive,name='ddlempexecall'),
    path('supplier/',views.supplierIndex,name='supplier'),
    path('suppliersummary/',views.supplierSumryIndex,name='suppliersummary'),
    path('productadd/',views.productadd, name='productadd'),
    path('productorservice/',views.productorservice, name='productorservice'),
    path('productdetails/',views.productdetails,name='productdetails'),
    path('categoryget/', views.categoryget, name='categoryget'),
    path('typeget/', views.typeget, name='typeget'),
    path('producttypeset/', transactionview.producttypeset, name='producttypeset'),
    path('productadd/', views.productadd, name='productadd'),
    path('Productsmry/', transactionview.Productsmry, name='Productsmry'),
    path('popupcarton/', views.Product_Add_Popupcarton, name="Product_Add_Popupcarton"),
    path('suppliermaster/',views.Supplier_Master,name='Supplier_Master'),
    path('popup3/', views.Product_Type_Popup, name="Product_Type_Popup"),
    path('popup2/', views.Product_Add_Popup, name="Product_Add_Popup"),
    path('supplierdetails/',views.supplierdetails,name='supplier_details'),
    path('set_state_dist_city_pincode/',views.SetCityPincode,name='Adding_New_City_Pincode'),
    path('product_specification/',views.prod_specification,name='prod_specification'),
    path('empactinact/', views.empactinact, name='employee_active_inactive'),
    path('common_summary/',views.common_summary,name='common_summary'),
    path('view_summary/',views.view_summary,name='view_summary'),
    path('view_summary_dynamic/',views.view_summary_dynamic,name='view_summary_dynamic'),
    path('insert_bank_branch/',views.insert_bank_branch,name='insert_bank_branch'),
    path('insert_paymode_details/',views.insert_paymode_details,name='insert_paymode_details'),
    path('insert_summary/',views.insert_summary,name='insert_summary'),
    path('update_summary/',views.update_summary,name='update_summary'),
    path('mst_hsn/',views.mst_hsn,name='mst_hsn'),
    path('mst_state_dist_city/',views.mst_state_dist_city,name='mst_state_dist_city'),
    path('hsn_data/',views.hsn_data,name='hsn_data'),
    path('set_mst_SDCP/',views.set_mst_SDCP,name='set_mst_SDCP'),#set_mst_State-Distric-City-Pincode
    path('mst_tax/',views.mst_tax,name='mst_tax'),
    path('tax_data/',views.tax_data,name='tax_data'),
    path('get_bus_seg/',views.get_bus_seg,name='get_bus_seg'),
    path('employeeupload/', views.emp_upload, name='emp_upload'),
    path('set_empupload/', views.set_empupload, name='set_empupload'),
    path('get_empupload/', views.get_empupload, name='get_empupload'),
    path('del_empupload/', views.del_empupload, name='del_empload'),
    path('saveemp/', views.saveemp, name='saveemp'),
    path('customerupload/',views.customerupload,name='customerupload'),
    path('custset/',views.custset,name='custset'),
    path('custupload/',views.custupload,name='custupload'),
    path('customersubmit/',views.customersubmit,name='customersubmit'),
    path('customerdelete/',views.customerdelete,name='customerdelete'),
    path('select_query_screen/', views.select_query_screen, name="select_query_screen"),

    # path('master_accesstoken/', views.master_accesstoken, name='master_accesstoken'),
    #path('mastersync_set/', views.mastersync_set, name='mastersync_set'),
    path('mastersync_employee_get/', coreViews.mastersync_employee_Data, name='mastersync_employee_Data'),
    path('mastersync_branch_get/', coreViews.mastersync_branch_Data, name='mastersync_branch_Data'),
    path('mastersync_gl_get/', coreViews.mastersync_gl_Data, name='mastersync_gl_Data'),
    path('agency/', views.agency, name='agency'),
    path('agencyupload/', views.agencyupload, name='agencyupload'),
    path('agencyset/', views.agencyset, name='agencyset'),
    path('SubAgency/', views.SubAgency, name='SubAgency'),
    path('deleteagency/', views.deleteagency, name='deleteagency'),
    path('customerupload/', views.customerupload, name='customerupload'),
    path('custset/', views.custset, name='custset'),

    # Courier
    path('mst_courier/',views.mst_courier,name='mst_courier'),
    path('get_courier_summary/', views.courier_summary_get, name='get_courier_summary'),
    path('courier_data/', views.courier_data, name='courier_set'),
    # Add Business Segment
    path('add_business_segment/', views.add_business_segment, name='add_business_segment'),
    path('fileUploadS3/', views.fileUploadS3, name='fileUploadS3'),
    path('common_s3_file_url_generate/', views.common_s3_file_url_generate, name='common_s3_file_url_generate'),
    path('common_s3_file_download/', views.common_s3_file_download, name='common_s3_file_download'),
    path('customer_query_screen/', views.customer_query_screen, name="customer_query_screen"),
    path('customer_query_screen_id/', views.customer_query_screen_id, name="customer_query_screen_id"),
    path('customer_query_screen_update/', views.customer_query_screen_update, name="customer_query_screen_update"),
    path('customer_query_screen_dependent/', views.customer_query_screen_dependent, name="customer_query_screen_dependent"),

    ]
